/** @format */

import Head from "next/head";
import Banner from "../components/Banner";
import styles from "../styles/Home.module.scss";

import Image from "next/image";
import HeroImage from "../public/static/hero-image.png";

const handleOnBannerButtonClick = () => console.log("Hi Banner button");

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Coffee Connoisseur</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <Banner buttonText={"View stores nearby"} handleOnClick={handleOnBannerButtonClick} />
        <div className={styles.heroImage}>
          <Image src={HeroImage} alt='' width={1200} height={500} />
        </div>
      </main>
    </div>
  );
}
